import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Sparkles, Calendar, Clock, MapPin, Wallet, ArrowRight, Loader2, ListTree } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";

const SavedTrips = () => {
  const { user } = useAuth();
  const [trips, setTrips] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user) return;
    
    const fetchTrips = async () => {
      const { data, error } = await supabase
        .from("trip_plans")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false });

      if (!error && data) {
        setTrips(data);
      }
      setLoading(false);
    };

    fetchTrips();
  }, [user]);

  if (loading) {
    return (
      <div className="min-h-screen bg-background pt-24 pb-12 flex items-center justify-center">
        <Loader2 className="h-12 w-12 text-primary animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background pt-24 pb-12">
      <div className="container mx-auto px-6 max-w-6xl">
        <div className="flex items-center gap-3 mb-8">
          <div className="p-3 bg-accent/10 text-accent rounded-xl">
            <Sparkles className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-3xl font-display font-bold">My Saved AI Trips</h1>
            <p className="text-muted-foreground">Revisit the itineraries generated by your personal AI assistant.</p>
          </div>
        </div>

        {trips.length === 0 ? (
          <div className="bg-card border border-border rounded-2xl p-12 flex flex-col items-center text-center shadow-sm">
            <ListTree className="h-16 w-16 text-muted-foreground/30 mb-4" />
            <h2 className="text-2xl font-bold mb-2">No trips planned yet</h2>
            <p className="text-muted-foreground mb-6">You haven't used the AI Trip Planner to create any itineraries yet.</p>
            <Link to="/planner">
              <Button size="lg" className="bg-primary text-primary-foreground font-bold">
                <Sparkles className="h-4 w-4 mr-2" /> Start Planning Now
              </Button>
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {trips.map((trip, idx) => (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.1 }}
                key={trip.id}
                className="bg-card overflow-hidden border border-border shadow-sm hover:shadow-card transition-all rounded-2xl flex flex-col"
              >
                <div className="p-6 flex-1 flex flex-col">
                  <div className="flex justify-between items-start mb-4">
                    <div className="bg-primary/10 text-primary px-3 py-1 rounded-full text-xs font-semibold whitespace-nowrap overflow-hidden text-ellipsis max-w-[200px]">
                      {trip.generated_itinerary.title || "Custom AI Trip"}
                    </div>
                  </div>
                  <h3 className="text-2xl font-display font-bold text-foreground mb-2 flex items-center gap-2">
                    <MapPin className="h-5 w-5 text-accent shrink-0" />
                    {trip.destination}
                  </h3>
                  <p className="text-muted-foreground text-sm flex-1 mb-6 line-clamp-3">
                    {trip.generated_itinerary.summary || `A beautifully detailed ${trip.duration} itinerary carefully curated based on your preferences.`}
                  </p>

                  <div className="grid grid-cols-2 gap-y-3 text-sm text-foreground font-medium bg-secondary p-4 rounded-xl mb-6">
                    <div className="flex items-center gap-2">
                       <Clock className="h-4 w-4 text-muted-foreground" />
                       {trip.duration}
                    </div>
                    <div className="flex items-center gap-2">
                       <Wallet className="h-4 w-4 text-muted-foreground" />
                       {trip.budget}
                    </div>
                    <div className="flex items-center gap-2">
                       <Calendar className="h-4 w-4 text-muted-foreground" />
                       {new Date(trip.created_at).toLocaleDateString()}
                    </div>
                     <div className="flex items-center gap-2 text-accent">
                       <Sparkles className="h-4 w-4" />
                       {trip.interests?.length > 0 ? `${trip.interests.length} Interests` : `General`}
                    </div>
                  </div>

                  <Link to="/planner" className="mt-auto">
                    {/* In a real implementation this would link to /saved-trips/:id to view the full JSON, but for now we link back to planner */}
                    <Button variant="outline" className="w-full flex justify-between items-center group hover:bg-primary hover:text-primary-foreground border-primary/20">
                      Generate Similar Trip <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
                    </Button>
                  </Link>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default SavedTrips;
